# Generated by Django 2.2.28 on 2025-03-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(default='None', max_length=255)),
                ('email', models.CharField(default='no.email@provided', max_length=127)),
                ('website', models.CharField(default='https://en.wikipedia.org/w/index.php?search=&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='This is an internship...', max_length=1023)),
                ('closing_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.FloatField()),
                ('address', models.CharField(default='None', max_length=255)),
                ('checklist', models.CharField(default='No extra items', max_length=1023)),
                ('slug', models.SlugField(unique=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legendary.Company')),
                ('user_ids', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('internship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legendary.Internship')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
