# Generated by Django 2.2.28 on 2025-03-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='data',
        ),
    ]
