# Generated by Django 2.2.28 on 2025-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0005_auto_20250323_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/images/generic_profile.jpg', upload_to='profile_images'),
        ),
    ]
