# Generated by Django 2.2.28 on 2025-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0006_auto_20250323_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='/images/generic_profile.jpg', upload_to='static/images/profile_images'),
        ),
    ]
